#!/bin/bash

# only proceed script when started not by pull request (PR)
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone local repo to "_site"
git clone .git --branch gh-pages _site

# build with Jekyll into "_site"
bundle exec jekyll build

# push to local repo
cd _site
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push origin gh-pages

# push to remote repo
git remote add upstream https://${GH_TOKEN}@github.com/ayastreb/11route.git
git push --quiet upstream gh-pages