#!/bin/bash

# only proceed script when started not by pull request (PR)
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# build site with jekyll, by default to `_site' folder
bundle exec jekyll build

# cleanup
rm -rf ../repo

#clone `master' branch of the repository using encrypted GH_TOKEN for authentication
git clone https://${GH_TOKEN}@github.com/ayastreb/11route.git ../repo

# copy generated HTML site
cp -R _site/* ../repo

# commit and push generated content to `gh-pages' branch
cd ../repo
git checkout gh-pages
git config user.email "anatoliy.yastreb@gmail.com"
git config user.name "Anatoliy Yastreb"
git add -A .
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --quiet origin gh-pages > /dev/null 2>&1